# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02af9113272fd0c070ff8e73ba1476c7f2280bac0eeda8fa304ca6c162b68c638c89681d95db4a84e8fd95bbb2af5a3a39ae5f56b396519b0774bef046b5e540

test:
  secret_key_base: 411879ed30047299af622a3f29b4401ef6fd5e8f02eed093bb2d87e44b7927801d106caf39ccd472f921f2d8403052c3068e8a126aeb8b0d414c2a21ee211e94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
